export const ENDPOINTS = {
    // USER
    FORGOT_PASSWORD: 'user/forgot-password',
    LOGIN: 'user/login',
    REGISTER: 'user/register',
    GET_DATA: 'user/fetch',
    // DISTANCE
    ADD_DISTANCE: 'distance/add',
    ASSIGN_DISTANCE: 'distance/assign',
    // GROUP
    GET_MEMBERS: 'group/get-members',
    RESET_DISTANCE: 'group/reset',
    EDIT_SETTINGS: 'group/update',
    JOIN_GROUP: 'user/change-group',
    VALIDATE_GROUP: 'group/validate-id',
    // PRESET
    GET_PRESETS: 'preset/get',
    ADD_PRESET: 'preset/add',
    EDIT_PRESET: 'preset/edit',
    DELETE_PRESET: 'preset/delete',
    // PETROL
    ADD_PETROL: 'petrol/add',
    CHECK_VALIDITY: 'petrol/check-validity',
    // INVOICES
    GET_INVOICES: 'invoices/get',
    GET_PUBLIC_INVOICES: 'invoices/public/get',
    SEND_REMINDER: 'invoices/alert',
    ASSIGN_INVOICE_DISTANCE: 'invoices/assign',
    // LOGS
    GET_LOGS: 'logs/get',
    EDIT_LOG: 'logs/edit',
    DELETE_LOG: 'logs/delete',
};
